export const colors = ["#e74c3c", "#3498db", "#27ae60", "#f39c12", "#9b59b6", "#1abc9c", "#e67e22"];

export const mapIdToName = (id: string) => {
  const mapping: Record<string, string> = {
    "province-1": "Yên Bái",
    "province-2": "Phú Thọ",
    "province-3": "Quảng Ninh",
    "province-4": "Khánh Hòa",
    "province-5": "Tiền Giang",
    "province-6": "Bà Rịa - Vũng Tàu",
    "province-7": "Bình Thuận",
    "province-8": "Hồ Chí Minh",
    "province-9": "Bến Tre",
    "province-10": "Sóc Trăng",
    "province-11": "Lai Châu",
    "province-12": "Sơn La",
    "province-13": "Thái Nguyên",
    "province-14": "Hà Nội",
    "province-15": "Hải Dương",
    "province-16": "Bắc Ninh",
    "province-17": "Hưng Yên",
    "province-18": "Vĩnh Phúc",
    "province-19": "Ninh Bình",
    "province-20": "Hà Nam",
    "province-21": "Hòa Bình",
    "province-22": "Bắc Giang",
    "province-23": "Thái Bình",
    "province-24": "Lâm Đồng",
    "province-25": "Bình Phước",
    "province-26": "Tây Ninh",
    "province-27": "Phú Yên",
    "province-28": "Bình Định",
    "province-29": "Hải Phòng",
    "province-30": "Gia Lai",
    "province-31": "Quảng Ngãi",
    "province-32": "Đồng Nai",
    "province-33": "Đồng Tháp",
    "province-34": "Cần Thơ",
    "province-35": "Long An",
    "province-36": "Hậu Giang",
    "province-37": "Bạc Liêu",
    "province-38": "Vĩnh Long",
    "province-39": "Hà Giang",
    "province-40": "Nam Định",
    "province-41": "Điện Biên",
    "province-42": "Lạng Sơn",
    "province-43": "Thanh Hóa",
    "province-44": "Bắc Kạn",
    "province-45": "Tuyên Quang",
    "province-46": "Hà Tĩnh",
    "province-47": "Nghệ An",
    "province-48": "Quảng Bình",
    "province-49": "Đắk Lắk",
    "province-50": "Ninh Thuận",
    "province-51": "Đắk Nông",
    "province-52": "Kon Tum",
    "province-53": "Quảng Nam",
    "province-54": "Quảng Trị",
    "province-55": "Thừa Thiên Huế",
    "province-56": "Kiên Giang",
    "province-57": "Đà Nẵng",
    "province-58": "An Giang",
    "province-59": "Cà Mau",
    "province-60": "Trà Vinh",
    "province-61": "Cao Bằng",
    "province-62": "Lào Cai",
    "province-63": "Bình Dương",
    "province-64": "Hoàng Sa",
    "province-65": "Trường Sa",
  };
  return mapping[id] || id;
};

export const specialProvinceMap: Record<string, string> = {
  "province-64": "province-57",
  "province-65": "province-4",
};
